services:
  db:
    image: postgres:16
    container_name: "em_postgres"
    environment:
      POSTGRES_USER: postgres,
      POSTGRES_PASSWORD: postgres,
      POSTGRES_DB: em
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data: